name: docker-ci

on:
  push:
    tags:
      # semver format, e.g.: v1.2.3
      - "v[0-9]+.[0-9]+.[0-9]+"


jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Parse image tag
        id: parse-tag
        shell: bash
        run: |
          echo 'base_ref ${{ github.ref_name }}'
          if [ '${{ github.ref_name }}' == '' ]; then
            echo 'Warning, input image tag empty! Falling back to short commit SHA.'
            IMAGE_TAG=$(git rev-parse --short HEAD)
          else
            IMAGE_TAG=${{ github.ref_name }}
          fi

          echo IMAGE_TAG = $IMAGE_TAG
